# Generated by Django 4.2.5 on 2023-10-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_alter_compra_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='direccion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='numero_telefono',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
